### ISSUE TITLE
Zen Coding for gedit 3.0

### ISSUE THREAD

**Issue by fedesilvaponte** [crittermike/zen-coding-gedit#15]
Hi, I don't know if this is the right place to put this, but after upgrading to gnome3 I cannot use zen coding anymore on gedit. 

Is there support to gedit 3.0 for this plugin?

Thanks

**Comment by flexgrip** [comment]
Me too. It is definitely not an installation issue. I know what I am doing and have modified several plugins for gedit.

I also tried installing it to the same directory that gedit pulls its repository installed plugins. No dice.

**Comment by flexgrip** [comment]
Ahh nevermind. Gobject introspection actually kills the party once again. Problem is we are using gnome3 a while its still a toddler. Here is where you can find the relevant information, plus a quote:

https://answers.launchpad.net/ubuntu/+source/gedit/+question/158045

"You have two choices:
A. I think you need to go back to Unity/gnome2 desktop
B. Update all scriptable/extendable/plugable apps to gnome3/

Gnome3 uses GObject Introspection exclusively to expose an app's API to other tools. The members of the Gedit project contributed to libpeas which is a new plugin/extension system to manage the integration of plugins. It is used by several apps. The gedit team then introduced a plugin API to gedit that simplifies the libpeas API for plugins. The errors you are seeing are because the plugin does not provide the correct methods (GeditAppActivatable, GeditWindowActivatable, GeditViewActivatable) to run with gedit.

All gedit plugin must be rewritten to the new API. Gedit default plugins are already updated, but you need to install the correct version (3.x). Very few plugins work with Gedit 3 at this moment."

Looks like if we want zencoding we need to be using scribes at the moment until everyone fixes their gedit plugins. I love when backwards compatibility is thrown out the window :)

**Comment by fedesilvaponte** [comment]
I guess I'll just wait until the plugins are updated to this new version.

Thanks for your help

El 17/06/11 02:22, flexgrip escribió:

> Ahh nevermind. Gobject introspection actually kills the party once again. Problem is we are using gnome3 a while its still a toddler. Here is where you can find the relevant information, plus a quote:
> 
> https://answers.launchpad.net/ubuntu/+source/gedit/+question/158045
> 
> "You have two choices:
> A. I think you need to go back to Unity/gnome2 desktop
> B. Update all scriptable/extendable/plugable apps to gnome3/
> 
> Gnome3 uses GObject Introspection exclusively to expose an app's API to other tools. The members of the Gedit project contributed to libpeas which is a new plugin/extension system to manage the integration of plugins. It is used by several apps. The gedit team then introduced a plugin API to gedit that simplifies the libpeas API for plugins. The errors you are seeing are because the plugin does not provide the correct methods (GeditAppActivatable, GeditWindowActivatable, GeditViewActivatable) to run with gedit.
> 
> All gedit plugin must be rewritten to the new API. Gedit default plugins are already updated, but you need to install the correct version (3.x). Very few plugins work with Gedit 3 at this moment."

## 

Federico Silva Ponte
www.fedesilva.com

**Comment by ghost** [comment]
Ubuntu 11.10 "Oneiric Ocelot" is [scheduled](https://wiki.ubuntu.com/OneiricReleaseSchedule) to be released on October 13, 2011 and will provide [only gedit 3](http://packages.ubuntu.com/oneiric/gedit).

**Comment by ghost** [comment]
Uhhh, just ran into this issue. :( Any chance we will see an update of the plugin in the near future? I really loved the ease, working with GNOME3 and gedit.

**Comment by aeischeid** [comment]
I am going to fork and try a couple things. porting to Gedit 3 shouldn't be to hard it looks like, but I am not fluent in python or gtk stuff so... 

http://www.micahcarrick.com/writing-plugins-for-gedit-3-in-python.html

https://live.gnome.org/PyGObject/IntrospectionPorting

**Comment by flexgrip** [comment]
Isn't it more about gobject (and the new stuff found in gnome 3 and unity) than gedit v3? I've read that if you are using gedit 3 on icewm the plugins all still work.

Keep in mind I could be very wrong :)

EDIT: All of this gobject crap and non-working plugins has put me on a quest for a new editor. Obviously gedit is the most lightweight in linux, but I recently found sublime text 2, which has zencoding and sparkup and a TON of stuff. I kinda like it. But I would love to get back to using gedit once all the plugins work.

**Comment by aeischeid** [comment]
yeah, could be. I know almost nothing about this type of programming.

**Comment by crittermike** [comment]
To anyone who might want to look into this, aeischeid has gotten a good head start over at https://github.com/mikecrittenden/zen-coding-gedit/pull/17

**Comment by aeischeid** [comment]
this branch may be farther along... https://github.com/rtlong/gmate/tree/master/plugins3/zencoding
