### ISSUE TITLE
Gedit v3 and this plugin

### ISSUE THREAD

**Issue by ZekMan** [crittermike/zen-coding-gedit#18]
New folder plugins in ubuntu 11.10:
~/.local/share/gedit/plugins

New regulations:
.gedit-plugin extension should be named .plugin
[Gedit Plugin] header should be [Plugin]
IAge=2 should be IAge=3
All plugins must have a .plugin file along side it.

But this does not help. The plugin does not work in gedit 3.
http://itmag.es/42H2K

**Comment by Thimoteus** [comment]
Check this one out: https://github.com/rtlong/gmate/tree/master/plugins3/zencoding

I'm using it with gedit 3. Only problem I found was <Alt>Right moves a word right (similarly with <Alt>Left) instead of moving to the next edit point.
I couldn't figure out why it was doing that, so I switched the next/previous edit point shortcuts.

**Comment by gnatih** [comment]
This one seems to work - https://github.com/mtrovo/zen-coding-gedit3.
