### ISSUE TITLE
People who put dashes in the names of python modules shall be shot.

### ISSUE THREAD

**Issue by cwillu** [crittermike/zen-coding-gedit#2]
mv zen-coding/ zen_coding/, and update zen-coding.gedit-plugin to match.  This will allow it to be imported normally without resorting to "stupid import tricks", making it easier to hack on and reuse.

**Comment by crittermike** [comment]
Done. I just went for zencoding instead of zen_coding since that seems to be direction ZC itself is moving (see http://github.com/sergeche/zen-coding/tree/master/python/ for example).

By the way, thanks SO MUCH for these couple bug reports. I have high hopes for this plugin so it's really good to know that I'm getting some eyes on it that aren't my own. I'm relatively new to Python so best practice stuff like this is new to me. Thanks again.
